//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSLogistics.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbs_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbs_Product()
        {
            this.Tbs_CartItem = new HashSet<Tbs_CartItem>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public string SKU { get; set; }
        public Nullable<int> Inventory { get; set; }
        public string Image { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<bool> IsFreeShip { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> Last_Updated_Date { get; set; }
        public Nullable<bool> IsActve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbs_CartItem> Tbs_CartItem { get; set; }
        public virtual Tbs_Category Tbs_Category { get; set; }
    }
}
