//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSLogistics.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbs_CartItem
    {
        public int ID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Tbs_Cart Tbs_Cart { get; set; }
        public virtual Tbs_Product Tbs_Product { get; set; }
    }
}
