//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSLogistics.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbs_Order
    {
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CartID { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string CancelBy { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelReason { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Tbs_Cart Tbs_Cart { get; set; }
    }
}
