//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSLogistics.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbs_Cart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbs_Cart()
        {
            this.Tbs_CartItem = new HashSet<Tbs_CartItem>();
            this.Tbs_Order = new HashSet<Tbs_Order>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public Nullable<int> TotalQty { get; set; }
        public Nullable<bool> IsCheckout { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbs_CartItem> Tbs_CartItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbs_Order> Tbs_Order { get; set; }
    }
}
