//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBSLogistics.WebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TBSDBEntities : DbContext
    {
        public TBSDBEntities()
            : base("name=TBSDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbs_Cart> Tbs_Cart { get; set; }
        public virtual DbSet<Tbs_CartItem> Tbs_CartItem { get; set; }
        public virtual DbSet<Tbs_Category> Tbs_Category { get; set; }
        public virtual DbSet<Tbs_Product> Tbs_Product { get; set; }
        public virtual DbSet<Tbs_Order> Tbs_Order { get; set; }
    }
}
